"""modified app init

Revision ID: 670a5696633c
Revises: eb39430352f8
Create Date: 2025-11-05 17:19:57.573828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '670a5696633c'
down_revision = 'eb39430352f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.drop_constraint('goal_task_id_fkey', type_='foreignkey')
        batch_op.drop_column('task_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('goal_task_id_fkey', 'task', ['task_id'], ['id'])

    # ### end Alembic commands ###
