"""adds goal model

Revision ID: eb39430352f8
Revises: f44a653f4245
Create Date: 2025-11-05 17:05:39.471471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb39430352f8'
down_revision = 'f44a653f4245'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('task_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'task', ['task_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('task_id')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
